name: "[backend] Verify pull request"
on: pull_request
jobs:
  preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g firebase-tools
      - run: npm install
      - run: npm install -w @amoschan/backend
      - run: npm run deploy -w @amoschan/backend
