name: "[common-admin] Verify pull request"
on: pull_request
jobs:
  test:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm install -w @amoschan/common-admin
      - run: npm test -w @amoschan/common-admin
        env:
          INSTAGRAM_API_HOST: ${{ vars.INSTAGRAM_API_HOST }}
          INSTAGRAM_USERNAME: ${{ vars.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
